### ISSUE TITLE
[IDEA] annual halloween and/or christmas theme?

### ISSUE THREAD

**Issue by TheLostProbe** [CelestiaProject/www#40]
as halloween and christmas approached, an idea came to my mind regarding themes for the website that are applied during the months of october and december. i have already started work on a halloween theme over at [TheLostProbe/www/tree/halloween](https://github.com/TheLostProbe/www/tree/halloween), but i have not started on a christmas theme. i would like to hear your thoughts on this. how would such a theme be applied? do we just like make a PR every october, or is there a more efficient way? and do you think such a thing is even necessary?

**Comment by TheLostProbe** [comment]
yes, i was thinking of something like that, but unfortunately i dont really have any js knowledge. so this will probably either have to wait until much later, when i have more js knowledge, or we can just PR the halloween theme for this year and then do the js approach next year

**Comment by 375gnu** [comment]
What about 7 billions people outside of west european world who doesn't celebrate these holidays?

**Comment by SevenSpheres** [comment]
> and do you think such a thing is even necessary?

No.

**Comment by TheLostProbe** [comment]
> What about 7 billions people outside of west european world who doesn't celebrate these holidays?

im fairly certain that more than 1 billion people on this planet celebrate them
> No.

when i say "you", im not referring to just any person who reads it, im referring to hleb and lev
