### ISSUE TITLE
Changes should be automatically reflected on the website

### ISSUE THREAD

**Issue by SevenSpheres** [CelestiaProject/www#6]
@Askaniy updated the download and news pages a month ago, but the website still hasn't changed. These pages will need to be updated again now that Celestia 1.6.2 is officially released. It would be easier for everyone if changes to this repository were automatically reflected on the website. (If this isn't possible the issue can be closed.)

**Comment by 375gnu** [comment]
good idea, this is rather easy  to implement

**Comment by 375gnu** [comment]
The side is automatically updated every hour since the other day so I closing this.
